### ISSUE TITLE
What must be done to run this in Linux?

### ISSUE THREAD

**Issue by themightyoarfish** [msracver/Deep-Exemplar-based-Colorization#1]
Since the code seems to be Caffe-based, what would be the steps needed to make this run on Linux?

**Comment by cddlyf** [comment]
Caffe is only used for calculating the flow and errorrec as the preprocessing step. So just reconfig the part for linux，the remaining is pytorch，which can support linux.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by gaojxx** [comment]
@themightyoarfish  Did you run it on Linux successfully? If yes, could you provide the link of your code? Thanks very much!

**Comment by themightyoarfish** [comment]
Didn't try, no.

**Comment by ncianeo** [comment]
https://github.com/msracver/Deep-Exemplar-based-Colorization/pull/21

After some modification of sources (deep image analogy and similarity combo), I managed to build this in linux.

**Comment by SibingWu** [comment]
> #21
> 
> After some modification of sources (deep image analogy and similarity combo), I managed to build this in linux.

Hi, I tried to run your linux+docker version code, but I encountered an error:
```
Traceback (most recent call last):
  File "../colorization_subnet/test.py", line 60, in <module>
    for iter, data in enumerate(data_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 434, in reraise
    raise exception
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/src/app/colorization_subnet/lib/TestDataset.py", line 117, in __getitem__
    errs, warp_ba, warp_aba = combo5_loader(combo_path, w, h)
  File "/src/app/colorization_subnet/lib/TestDataset.py", line 52, in combo5_loader
    img_data_ndarray = cv2.cvtColor(img_data_ndarray, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(3.4.8) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```

I print out the intermediate variables, and found out that
```
file_bytes: [89 80 69 ... 62 10 10]
file_bytes.shape: (127386,)
img_data_ndarray: None # img_data_ndarray = cv2.imdecode(file_bytes, cv2.IMREAD_COLOR)
```
I did some research but did not find a workable solution. 

Could you please suggest on this? Thank you so much!!
